#!/usr/bin/env bash
# Set up GitHub MCP Server for Claude Code
# See: https://github.com/github/github-mcp-server/blob/main/docs/installation-guides/install-claude.md
#
# SECRETS: the token is never passed to this script. It stays in 1Password, and
# Claude Code fetches it at connection time through the MCP `headersHelper`
# hook, so it never appears in argv, in shell history, or in ~/.claude.json.
#
# Store the PAT in 1Password, copy its secret reference (right click the field >
# "Copy Secret Reference"), and point this script at it:
#   GITHUB_PAT_OP_REF='op://Private/GitHub PAT/token' bash scripts/setup-github-mcp.sh

set -euo pipefail

OP_REF="${GITHUB_PAT_OP_REF:-op://Private/GitHub PAT/token}"

for required in claude op; do
    if ! command -v "$required" &>/dev/null; then
        echo "Error: '$required' not found." >&2
        case "$required" in
            claude) echo "Install Claude Code first (e.g. via Zed)." >&2 ;;
            op) echo "Install the 1Password CLI: brew install --cask 1password-cli" >&2 ;;
        esac
        exit 1
    fi
done

# The reference is embedded in a generated shell script, so refuse anything that
# would need escaping there.
if [[ "$OP_REF" != op://* ]] || [[ "$OP_REF" == *[\"\$\`\\]* ]]; then
    echo "Error: GITHUB_PAT_OP_REF must be an op:// reference without \" \$ \` or \\ characters." >&2
    echo "Got: $OP_REF" >&2
    exit 1
fi

# Fail here, with a clear message, rather than at Claude Code startup.
if ! op read --no-newline "$OP_REF" >/dev/null; then
    echo "" >&2
    echo "Error: could not read a token from '$OP_REF'." >&2
    echo "Create a PAT at: https://github.com/settings/personal-access-tokens/new" >&2
    echo "Scopes: repo, read:org" >&2
    echo "Save it in 1Password, then re-run with GITHUB_PAT_OP_REF set to its secret reference." >&2
    exit 1
fi

# Claude Code runs this on every connection and merges its stdout into the
# request headers, so the token only ever lives in memory.
HELPER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/claude"
HELPER="$HELPER_DIR/github-mcp-headers.sh"
mkdir -p "$HELPER_DIR"
cat > "$HELPER" <<HELPER_SCRIPT
#!/usr/bin/env bash
# Generated by new-mac-setup scripts/setup-github-mcp.sh. Do not add a token
# here: it is read from 1Password on each run.
set -euo pipefail
# python3 does the JSON encoding so that a token containing quotes or
# backslashes still produces a valid header object.
op read --no-newline "$OP_REF" |
    python3 -c 'import json, sys; print(json.dumps({"Authorization": "Bearer " + sys.stdin.read()}))'
HELPER_SCRIPT
chmod 700 "$HELPER"

# Remove existing server if present (idempotent)
claude mcp remove github --scope user 2>/dev/null || true

# Add GitHub MCP server (remote HTTP - no Docker required)
claude mcp add-json github \
    "{\"type\":\"http\",\"url\":\"https://api.githubcopilot.com/mcp\",\"headersHelper\":\"$HELPER\"}" \
    --scope user

echo "GitHub MCP server configured, reading its token from $OP_REF."
echo "Restart Claude Code and run 'claude mcp list' to verify."
